global:
  scrape_interval: 10s
rule_files:
 - rules.yml
alerting:
  alertmanagers:
  - path_prefix: /alertmanager/
    static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
 - job_name: prometheus
   metrics_path: /prometheus/metrics
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets:
       - example.host:9100
